// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  ai: [{type: 'autogenerated', dirName: '.'}],
  // Python 知识库的侧边栏
  willdocs: [{type: 'autogenerated', dirName: '.'}],

  // JavaScript 知识库的侧边栏
  javascript: [{type: 'autogenerated', dirName: '.'}],

  // Django 知识库的侧边栏
  django: [{type: 'autogenerated', dirName: '.'}],
  
  // 前端开发知识库的侧边栏
  // 您原来的配置是 dirName: 'willdocs'，如果您的 frontend 文档确实在 'knowledge-bases/frontend/willdocs/' 目录下，可以保留。
  // 否则，使用 '.' 会更简单，它代表在 'knowledge-bases/frontend/' 目录下自动生成。
  frontend: [{type: 'autogenerated', dirName: '.'}],

  golang: [{type: 'autogenerated', dirName: '.'}],
  java: [{type: 'autogenerated', dirName: '.'}],
  vuejs: [{type: 'autogenerated', dirName: '.'}],


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
